#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.

# Check if argument is provided
if [ -z "$1" ]; then
	echo "Usage: $0 {IP_ADDRESS}"
	exit 1
fi

# Ping the IP 5 times
ping -c 5 "$1"
