#!/usr/bin/env bash
# this script displays the content of the file /etc/password, using the while loop + IFS.

while IFS=':' read -r username _ uid gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $info"
done </etc/passwd
