#!/usr/bin/env bash
# Display "Best School" 10 times, output "Hi" on the 9th iteration
i=1
while [ $i -le 10 ]; do
    if [ $i = 10 ]; then
        echo "Hi"
    fi
    echo "Best School"
    i=$((i + 1))
done
