#!/usr/bin/env bash

# Change localhost and facebook.com IP resolutions
cp /etc/hosts ~/hosts.new

# Change localhost IP to 127.0.0.2
sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/g' ~/hosts.new
# Change facebook.com IP to 8.8.8.8
echo "8.8.8.8		facebook.com" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts
