#!/usr/bin/env bash
# This bash script modifies an IP address
cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1/127.0.0.2/g'  ~/hosts.new
sudo sed -i 's/[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+/8.8.8.8/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
# Clear DNS cache
sudo systemd-resolve --flush-caches