#!/usr/bin/env bash
# Displays all acive IPv4 addresses on the machine.

# Retrieve IPv4 addresses using ifconfig and grep
ipv4_addresses=$(ifconfig | grep -oE 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}' | grep -v '127.0.0.1')

# Display the retrieved IPv4 addresses
echo "$ipv4_addresses"
